import turtle
turtle.setup(1000,1000,0,0)
mitul=turtle.Turtle()
mitul.width(8)
mitul.color("red")
new=turtle.getscreen()
mitul.speed(4)
new.bgcolor("lightblue")
# Hidden Work(penup)
mitul.left(180)
mitul.penup()
mitul.forward(300)
mitul.right(90)
mitul.forward(100)
mitul.pendown()
# Printing H
#start to draw
mitul.forward(50)
mitul.right(90)
mitul.forward(50)
mitul.left(90)
mitul.forward(50)
mitul.left(90)
mitul.penup()
mitul.forward(50)
mitul.left(90)
mitul.pendown()
mitul.forward(50)
mitul.left(90)
mitul.forward(50)
mitul.right(90)
mitul.forward(50)
# printing A
mitul.penup()
mitul.left(90)
mitul.forward(15)
mitul.pendown()
mitul.left(70)
mitul.forward(110)
mitul.right(70)
mitul.right(70)
mitul.forward(110)
mitul.left(180)
mitul.forward(55)
mitul.left(70)
mitul.forward(38)
mitul.left(70)
mitul.penup()
mitul.forward(55)
mitul.left(110)
mitul.forward(100)
# printing P
mitul.left(90)
mitul.pendown()
mitul.forward(100)
mitul.right(90)
mitul.forward(50)
mitul.right(20)
mitul.forward(20)
mitul.right(70)
mitul.forward(40)
mitul.right(70)
mitul.forward(20)
mitul.right(20)
mitul.forward(50)
mitul.left(90)
mitul.forward(50)
mitul.left(90)
mitul.penup()
mitul.forward(100)
# printing P
mitul.left(90)
mitul.pendown()
mitul.forward(100)
mitul.right(90)
mitul.forward(50)
mitul.right(20)
mitul.forward(20)
mitul.right(70)
mitul.forward(40)
mitul.right(70)
mitul.forward(20)
mitul.right(20)
mitul.forward(50)
mitul.left(90)
mitul.forward(50)
mitul.left(90)
mitul.penup()
mitul.forward(100)
# printing Y
mitul.forward(20)
mitul.pendown()
mitul.left(90)
mitul.forward(50)
mitul.left(30)
mitul.forward(60)
mitul.backward(60)
mitul.right(60)
mitul.forward(60)
mitul.backward(60)
mitul.left(30)
# go to Home
mitul.penup()
mitul.home()
mitul.color("orange")
new.bgcolor("lightgreen")
# setting second row
mitul.backward(300)
mitul.right(90)
mitul.forward(60)
# printing B
mitul.pendown()
mitul.forward(100)
mitul.right(160)
mitul.forward(100)
mitul.left(160)
mitul.forward(100)
# go to Home
mitul.penup()
mitul.home()
# setting second row
mitul.backward(300)
mitul.right(90)
mitul.forward(60)
# printing B
mitul.pendown()
mitul.forward(100)
mitul.right(160)
mitul.forward(100)
mitul.left(160)
mitul.forward(100)
# go to Home
mitul.penup()
mitul.home()